//
//  MainViewController.m
//  JackIt
//
//  Created by Alexander Joo on 1/19/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import "MainViewController.h"


@implementation MainViewController


/*
// Implement viewDidLoad to do additional setup after loading the view, typically from a nib.
- (void)viewDidLoad {
	[super viewDidLoad];
}
*/

// Initializes the game if not yet present
- (Game *)theGame {
	if (!theGame)
    {
        // This initializes the game, dude, scene, event library
		theGame = [[Game alloc] init];
        gameStarted = NO;
    }
	return theGame;
}

// This is currently what it takes to start the game--this could 
// eventually be moved to "viewDidLoad" to autostart
- (IBAction)ticklePickle:(UIButton *)sender {
    theGame = [self theGame];
    gameStarted = YES;
    int tickNumber;
    // Game loop goes on here
    while (gameStarted)
    {
        tickNumber = [theGame goTick];
        tickCounter.text = [NSString stringWithFormat:@"Current tick: %i", tickNumber];
        excitementCounter.text = [NSString stringWithFormat:@"%f",[[theGame gameDude] excitement]];
//      [excitementBar setValue:[[theGame gameDude] excitement]/100.0];
        
        //input handler
        // wait to finish tick time
    }
}

// Should this only work if the game is started?
- (IBAction)setExcitementButton:(UIButton *)sender {
    if (!gameStarted) // Do nothing if the game hasn't started
        return;
    else // If the game has started, set the excitement value
    {
        NSString *value = [[sender titleLabel] text];
        NSLog(@"The excitement value set to: %@", value);        
        [[theGame gameDude] setExcitement:[value floatValue]];
    }
    
}

// ALL THE BELOW WERE AUTOGENERATED

- (void)flipsideViewControllerDidFinish:(FlipsideViewController *)controller {
    
	[self dismissModalViewControllerAnimated:YES];
}

// This is the (i) button that switches to the flipside view
- (IBAction)showInfo:(id)sender {    
	
	FlipsideViewController *controller = [[FlipsideViewController alloc] initWithNibName:@"FlipsideView" bundle:nil];
	controller.delegate = self;
	
	controller.modalTransitionStyle = UIModalTransitionStyleFlipHorizontal;
	[self presentModalViewController:controller animated:YES];
	
	[controller release];
}


- (void)didReceiveMemoryWarning {
	// Releases the view if it doesn't have a superview.
    [super didReceiveMemoryWarning];
	
	// Release any cached data, images, etc. that aren't in use.
}


- (void)viewDidUnload {
	// Release any retained subviews of the main view.
	// e.g. self.myOutlet = nil;
}


/*
// Override to allow orientations other than the default portrait orientation.
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
	// Return YES for supported orientations.
	return (interfaceOrientation == UIInterfaceOrientationPortrait);
}
*/


- (void)dealloc {
    [super dealloc];
}


@end
