//
//  PlayViewController.h
//  JackIt
//
//  Created by Alexander Joo on 1/19/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import <CoreMotion/CMMotionManager.h>
#import <Foundation/Foundation.h>
#import <iAd/iAd.h>
#import "FlipsideViewController.h"
#import "Game.h"
#define TICKDURATION 0.03 // this is in seconds

@interface MainViewController : UIViewController <FlipsideViewControllerDelegate> {
    IBOutlet UILabel *excitementCounter; // This is the "arousal number"
    IBOutlet UILabel *tickCounter; // This is the game tick
    IBOutlet UILabel *decayValue;
    IBOutlet UILabel *accelData;
    IBOutlet UILabel *twistData;
    IBOutlet UILabel *gameTime;
    IBOutlet UIProgressView *excitementBar; // This is a visual representation of arounsal
    
    // Core came objects
    Game *theGame; // a pointer to a game object
    CMMotionManager *motionManager;
    CMDeviceMotion *deviceMotion;
    
    // Core game data
    NSString* currentExcitement; // May or may not be useful
    NSTimer* gameTimer;
    double acceleration[3];
    Byte currentInputs; // holds the current state of all excitement inputs
    CGFloat gameTimeInSeconds;
}

// General behavioral functions
- (void)viewDidAppear:(BOOL)animated;
- (BOOL)canBecomeFirstResponder;

// This function starts the game
- (IBAction)ticklePickle:(UIBarButtonItem *)sender;

- (IBAction)setExcitementButton:(UIButton *)sender;

//- (IBAction)setDecayConstant:(UISlider *)sender;

// I don't know what this one does, it was autogenerated
- (IBAction)showInfo:(id)sender;

- (void)gameLoop;

@end
