//
//  MainViewController.h
//  JackIt
//
//  Created by Alexander Joo on 1/19/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import "FlipsideViewController.h"
#import "Game.h"

@interface MainViewController : UIViewController <FlipsideViewControllerDelegate> {
    IBOutlet UILabel *excitementCounter;
    IBOutlet UIProgressView *excitementBar;
    Game *theGame;
}

// This function starts the game
- (IBAction)ticklePickle:(UIButton *)sender;

// I don't know what this one does, it was autogenerated
- (IBAction)showInfo:(id)sender;

@end
