//
//  MainViewController.m
//  JackIt
//
//  Created by Alexander Joo on 1/19/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import "MainViewController.h"


@implementation MainViewController

// Initializes the game if not yet present
- (Game *)theGame {
	if (!theGame)
    {
        // This initializes the game, dude, scene, event library
		theGame = [[Game alloc] init];
        gameTimer = [NSTimer scheduledTimerWithTimeInterval:0.05 target:self selector:@selector(gameLoop) userInfo:nil repeats:(YES)];
        

    }
	return theGame;
}


- (void)viewDidLoad {
	[super viewDidLoad];

    // This initializes the game object
    theGame = [self theGame];
}

// Starts game if not started, pauses if it is started
- (IBAction)ticklePickle:(UIButton *)sender {
//    NSInteger tickNumber;
    if (theGame.gameState == JIGameNotStarted)
        theGame.gameState = JIGameStarted;
    else if (theGame.gameState == JIGameStarted)
        theGame.gameState = JIGamePaused;
    
    //input handler
}

- (IBAction)setDecayValue:(UISlider *)sender {
    //[theGame gameDude].decayConstant = sender.value;
    //decayValue.text = [NSString stringWithFormat:@"%f", sender.value];
}

- (void) gameLoop {
    [theGame goTick];
    
    // These are UI outputs based on game state
    tickCounter.text = [NSString stringWithFormat:@"Current tick: %i", theGame.tick];
    excitementCounter.text = [NSString stringWithFormat:@"%f",[[theGame gameDude] excitement]];
    excitementBar.progress = [[theGame gameDude] excitement] * 0.01;
    
}


// Should this only work if the game is started?
- (IBAction)setExcitementButton:(UIButton *)sender {
    NSString *value = [[sender titleLabel] text];
    NSLog(@"The excitement value set to: %@", value);        
    [[theGame gameDude] setExcitement:[value floatValue]];
    
}

// ALL THE BELOW WERE AUTOGENERATED

- (void)flipsideViewControllerDidFinish:(FlipsideViewController *)controller {
    
	[self dismissModalViewControllerAnimated:YES];
}

// This is the (i) button that switches to the flipside view
- (IBAction)showInfo:(id)sender {    
    
    
    /* //This code ends the game if it is running
    if ((theGame.gameState == JIGameStarted)||(theGame.gameState == JIGamePaused))
        theGame.gameState = JIGameOver;
    */
    
	FlipsideViewController *controller = [[FlipsideViewController alloc] initWithNibName:@"FlipsideView" bundle:nil];
	controller.delegate = self;
	
	controller.modalTransitionStyle = UIModalTransitionStyleFlipHorizontal;
	[self presentModalViewController:controller animated:YES];
	
	[controller release];
}


- (void)didReceiveMemoryWarning {
	// Releases the view if it doesn't have a superview.
    [super didReceiveMemoryWarning];
	
	// Release any cached data, images, etc. that aren't in use.
}


- (void)viewDidUnload {
	// Release any retained subviews of the main view.
	// e.g. self.myOutlet = nil;
}


/*
// Override to allow orientations other than the default portrait orientation.
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
	// Return YES for supported orientations.
	return (interfaceOrientation == UIInterfaceOrientationPortrait);
}
*/


- (void)dealloc {
    [super dealloc];
    [theGame release];
}


@end
